namoldak/Frontend

src/components/feature/login/Login.jsx
=> ✨ Feature login Validation

src/api/authAsync.jsx, src/components/feature/login/Login.jsx
=> ✨ Feat KaKao user nickname

src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomAll.jsx, src/pages/GameRoom.jsx
=> 🔧 Add GameRoomAll component//게임룸있던 컴포넌트 합침

.eslintrc.js, src/components/common/Modals/CreateRoomModal.jsx, src/components/common/Modals/GameAnswerModal.jsx, src/components/common/Modals/GameModal.jsx, src/components/common/Modals/Modal.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomAll.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomChoice.jsx, src/components/feature/RoomList/RoomListCards/RoomListCard.jsx, src/components/feature/login/Login.jsx, src/components/feature/signUp/Signup.jsx, src/redux/modules/roomSlice.jsx, src/utils/cookies.jsx
=> Game room/2

src/components/common/Modals/InGameModal/GameAnswerModal.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx, src/components/feature/login/Login.jsx
정답이 틀렸을 경우 계속 라운드가 돌아가는거 까지 구현 완료 되었습니다. 고생하셨어요
=> ✨ (게임로직) 정답 제출 기능 추가

src/components/common/Input.jsx, src/components/feature/login/Login.jsx, src/styles/theme.js
- Input (공통 컴포넌트) css update
- theme > colors 추가
=> 💄 Update Login UI

package.json, src/components/common/Modals/InGameModal/GameAnswerModal.jsx, src/components/common/Toast/ToastMessage.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx, src/pages/SignupPage.jsx
스킵, 엔드게임 추가 및 게임 토스트 메세지 설정 ver 1.0
=> ✨Feat: skip, endGame + in game toast message

src/components/feature/GameRoom/UserCardsAndChatBox/ChatBox.jsx, src/components/feature/RoomList/RoomListCards/Room.jsx, src/components/feature/RoomList/RoomListCards/RoomListCard.jsx, src/components/feature/RoomList/RoomListHeader/SearchRoom.jsx, src/redux/modules/roomSlice.jsx
searchRoom 기능 버그 수정 및 searchRoom input 부분 common component > styled component로 변경했습니당!
=> 🐛Fix searchRoom bug

src/components/feature/GameRoom/TitleAndTimer/SpotTimer.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/ChatBox.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx
=> 🩹 fix simple

src/components/common/Modals/BasicModal/RuleModal.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx, src/components/feature/RoomList/RoomListCards/RoomListCard.jsx, src/pages/SignupPage.jsx
=> 🐛 바이크 버튼 오류 수정

src/api/authAsync.jsx, src/api/core/axios.js, src/components/common/Modals/BasicModal/CreateRoomModal.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx, src/components/feature/login/Login.jsx, src/pages/SignupPage.jsx, src/redux/modules/roomSlice.jsx
alert 전부 toast message로 바꿨습니다~
=> 🩹 simple fix: alert > toast message

src/components/common/Modals/BasicModal/MyPageModal.jsx, src/components/feature/RoomList/Community/Card.jsx, src/components/feature/RoomList/Community/CardList.jsx, src/components/feature/RoomList/RoomListHeader/Header.jsx, src/components/feature/signUp/SignUp.jsx, src/pages/CommunityPage.jsx, src/pages/SignupPage.jsx, src/shared/Router.jsx
1. 커뮤니티 페이지 만들어서 router에 추가!
2. 약간의 코드 수정 (mypagemodal 변수 명 변경)
=> ✨Feat: add community related components (list & page)

src/components/common/Modals/BasicModal/SettingModal.jsx, src/components/feature/RoomList/RoomListHeader/RoomListTopBar.jsx, src/components/feature/landing/MySettingTabs/LogOutTab.jsx
=> 🐛 fix bug - modal close when logout

src/components/feature/Community/Post/WritePost.jsx
=> 💄 포스트 작성 UI 작업

src/utils/date.js
=> 👔 Add settingdate

src/components/feature/Community/Post/Post.jsx, src/components/feature/landing/MySettingTabs/LogOutTab.jsx
=> ♻️ Refactor : LogOutTab

src/components/feature/Community/Comment/Comment.jsx, src/components/feature/Community/Comment/CreateComment.jsx, src/components/feature/Community/Pagination.jsx, src/components/feature/Community/Post/PostDetail.jsx, src/components/feature/Community/PostList.jsx
=> 🐛 fix bug: post, edit, delete comment

src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx, src/redux/modules/postSlice.jsx, src/redux/modules/roomSlice.jsx
stomp 오류 수정 (thanks to 정민, 수빈 and myself 😉)
=> 🐛 fix bug:  stomp

src/api/core/axios.js, src/components/feature/GameRoom/UserCardsAndChatBox/ChatBox.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx
- gameRoomRTC에 type stupid 추가했습니다 (게임 종료 시 너네 다 바보 메세지 송출)
- 양계장 주인이 메세지 보낼 경우 채팅 색상 변경 (중첩 삼항연산자 사용)
=> 👔 Update: gaemRoomRTC add case STUPID

src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx, src/components/feature/RoomList/RoomListCards/Room.jsx
세션스토리지에 owner가 자꾸 저장이 안되어서 잠시 owner 변수 빼고 전부 sessionStorage.getItem('owner')로 변경해놨어요 일단
=> remove gameRoomRTC owner variable for now

src/components/common/Layout/Layout.jsx, src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx, src/components/feature/RoomList/RoomListCards/Room.jsx, src/redux/modules/errorToastMsg.jsx
방금 머지하고 conflict 났던 코드 수정했습니다!
(refresh token, axios 제외)
=> 🩹 simple fix - fix conflict code after merge

src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx
콘솔 지움
alert => toast msg
효과음 case별로 추가
=> <0001fa79> simple fix - gameRoomRTC effect sound, delete console.log

src/components/feature/GameRoom/UserCardsAndChatBox/GameRoomRTC.jsx
=> 🩹 simple fix : sound effect

public/index.html, src/api/authAsync.jsx, src/api/core/axios.js, src/components/common/Modals/BasicModal/DeleteKaKaoAccountModal.jsx
카카오 연결끊기 요청 시, 서버에서도 회원 탈퇴가 진행되는 api 요청 추가했습니다~
=> 👔 Update: deleteKakaoMember additional work - delete request to server

src/components/GameRoom/GameRoomRTC.jsx
GameRoomRTC 컴포넌트 안의 긴 로직을 가진 함수들 useCallBack 사용하여 선언 하여 컴포넌트 리렌더링시 재선언을 제한하였습니다
=> 🚀 게임방 성능 최적화

src/App.jsx, src/components/GameRoom/GameRoomRTC.jsx, src/components/common/Layout/PostWrapper.jsx, src/components/common/Modals/BasicModal/DeleteKaKaoAccountModal.jsx, src/hooks/usePreventRefesh.jsx
gameRoomRTC - useCallback 이전 버전으로 롤백
필요없는 코드 삭제
=> 🔥 delete unnecessary codes

src/components/GameRoom/GameRoomRTC.jsx, src/components/GameRoom/UserCardsAndChatBox/ChatBox.jsx, src/components/common/Modals/BasicModal/CreateRoomModal.jsx
=> 🩹 fix-simple: chatbubble css, create gameRoom owner info

src/utils/cookies.jsx
=> 🐛 Fix a bug
